import { IPost } from "./interfaces/IPost";

export const posts: IPost[] = [
  {
    title: "The Rise of Edge Computing in 2025",
    slug: "the-rise-of-edge-computing-in-2025",
    author: "Lucas Rossi",
    date: "2025-01-18",
    category: "Cloud Computing",
    thumbnail: "/images/thumbnails/edge-computing.jpg",
  },
  {
    title: "Building Scalable APIs with GraphQL",
    slug: "building-scalable-apis-with-graphql",
    author: "James Miller",
    date: "2024-12-02",
    category: "APIs",
    thumbnail: "/images/thumbnails/graphql.jpg",
  },
  {
    title: "AI-Powered Chatbots: Enhancing Customer Support",
    slug: "ai-powered-chatbots-enhancing-customer-support",
    author: "Melissa Bianchi",
    date: "2024-11-14",
    category: "AI/ML",
    thumbnail: "/images/thumbnails/ai-chatbots.jpg",
  },
  {
    title: "Serverless Functions: When and How to Use Them",
    slug: "serverless-functions-when-and-how-to-use-them",
    author: "Robert Carter",
    date: "2025-02-01",
    category: "Serverless",
    thumbnail: "/images/thumbnails/serverless.jpg",
  },
  {
    title: "Modern DevOps Pipelines: Best Practices for 2025",
    slug: "modern-devops-pipelines-best-practices-for-2025",
    author: "Agustín Romano",
    date: "2024-10-28",
    category: "DevOps",
    thumbnail: "/images/thumbnails/devops-pipeline.jpg",
  },
  {
    title: "Rust for Web Developers: A Gentle Introduction",
    slug: "rust-for-web-developers-a-gentle-introduction",
    author: "Daniel Cooper",
    date: "2024-09-07",
    category: "Programming Languages",
    thumbnail: "/images/thumbnails/rust-webdev.jpg",
  },
  {
    title: "Data Privacy in the Age of AI",
    slug: "data-privacy-in-the-age-of-ai",
    author: "Caro Lombardi",
    date: "2024-12-21",
    category: "Cybersecurity",
    thumbnail: "/images/thumbnails/data-privacy.jpg",
  },
  {
    title: "Next.js 15: What's New and Why It Matters",
    slug: "nextjs-15-whats-new-and-why-it-matters",
    author: "Matthew Harris",
    date: "2025-01-05",
    category: "Next.js",
    thumbnail: "/images/thumbnails/nextjs15.jpg",
  },
  {
    title: "Designing Accessible Web Interfaces",
    slug: "designing-accessible-web-interfaces",
    author: "Sofía Giordano",
    date: "2024-08-30",
    category: "Web Design",
    thumbnail: "/images/thumbnails/accessible-web.jpg",
  },
  {
    title: "The Future of Quantum Computing in Business",
    slug: "the-future-of-quantum-computing-in-business",
    author: "Jonathan Lee",
    date: "2024-11-03",
    category: "Quantum Computing",
    thumbnail: "/images/thumbnails/quantum-computing.jpg",
  },
  {
    title: "From Monolith to Microservices: A Migration Guide",
    slug: "from-monolith-to-microservices-a-migration-guide",
    author: "Martín Bellini",
    date: "2024-07-15",
    category: "Software Architecture",
    thumbnail: "/images/thumbnails/microservices.jpg",
  },
  {
    title: "Improving Frontend Performance with Code Splitting",
    slug: "improving-frontend-performance-with-code-splitting",
    author: "Elizabeth Scott",
    date: "2024-09-22",
    category: "Performance",
    thumbnail: "/images/thumbnails/code-splitting.jpg",
  },
]